name: Build and Deploy Dev

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '21.x'
        cache: npm
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and Push Docker image
      run: |
        docker buildx build --platform linux/amd64 --push --tag tnfus916/whereqr-frontend:latest -f Dockerfile .
    
    - name: Deploy to NCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/server_key
        chmod 600 ~/.ssh/server_key
        ssh-keyscan -p 12321 210.89.181.89 >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/server_key -p 12321 root@210.89.181.89 '
          echo "Connected to NCP Server"
          # 이미지 Pull 및 컨테이너 재시작
          docker pull tnfus916/whereqr-frontend:latest
          docker stop backend || true
          docker compose up -d
          '
