name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 21.x]

    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '21.x'
        cache: npm
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/whereqr-frontend:latest
      
    - name: Deploy to NCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/server_key
        chmod 600 ~/.ssh/server_key
        ssh-keyscan -p 12321 210.89.181.89 >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/server_key -p 12321 root@210.89.181.89 '
          echo "Connected to NCP Server"
          docker pull tnfus916/whereqr-frontend:latest
          echo "Docker image pull: $?"
          docker stop frontend || true
          echo "Docker container stop: $?"
          docker rm frontend || true
          echo "Docker container removal: $?"
          docker run -d --name frontend -p 3000:3000 tnfus916/whereqr-frontend:latest
          echo "Docker container run: $?"
